/* 
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Squiggle.Api;
using Squiggle.Model;
using Squiggle.Client;
using System.Reflection;

namespace Squiggle.Test
{
    /// <summary>
    ///  Class for testing GlobalTemplateResponseSingle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GlobalTemplateResponseSingleTests
    {
        // TODO uncomment below to declare an instance variable for GlobalTemplateResponseSingle
        //private GlobalTemplateResponseSingle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GlobalTemplateResponseSingle
            //instance = new GlobalTemplateResponseSingle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GlobalTemplateResponseSingle
        /// </summary>
        [Test]
        public void GlobalTemplateResponseSingleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GlobalTemplateResponseSingle
            //Assert.IsInstanceOfType<GlobalTemplateResponseSingle> (instance, "variable 'instance' is a GlobalTemplateResponseSingle");
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
