/* 
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Squiggle.Api;
using Squiggle.Model;
using Squiggle.Client;
using System.Reflection;

namespace Squiggle.Test
{
    /// <summary>
    ///  Class for testing ResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseLinksTests
    {
        // TODO uncomment below to declare an instance variable for ResponseLinks
        //private ResponseLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseLinks
            //instance = new ResponseLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseLinks
        /// </summary>
        [Test]
        public void ResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseLinks
            //Assert.IsInstanceOfType<ResponseLinks> (instance, "variable 'instance' is a ResponseLinks");
        }

        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Test]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Test]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Last'
        /// </summary>
        [Test]
        public void LastTest()
        {
            // TODO unit test for the property 'Last'
        }

    }

}
